## Importing the Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the Dataset

In [2]:
dataset = pd.read_csv('heart.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]


In [4]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0]


## Taking care of missing data

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x)
x = imputer.transform(x)

## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [8]:
print(x_train)

[[-1.32773282 -1.43641607  0.98584243 ... -0.66169316 -0.70710678
  -0.46472917]
 [ 1.24903178 -1.43641607  0.98584243 ... -0.66169316  0.26516504
  -0.46472917]
 [ 0.35276583  0.69617712  0.98584243 ...  0.95577901 -0.70710678
  -0.46472917]
 ...
 [ 0.12869935  0.69617712  1.94013791 ... -0.66169316 -0.70710678
   1.14190596]
 [-0.87959984  0.69617712  0.98584243 ...  0.95577901 -0.70710678
  -0.46472917]
 [ 0.35276583  0.69617712  0.03154696 ... -0.66169316 -0.70710678
  -0.46472917]]


In [9]:
print(x_test)

[[ 1.69716475  0.69617712 -0.92274852  0.77251645 -1.36354075 -0.41803981
   0.90163913 -1.07375268  1.40984195  1.2900049  -2.27916533 -0.70710678
   1.14190596]
 [ 1.02496529  0.69617712  1.94013791  2.23625729 -0.3703119  -0.41803981
  -0.97936664  0.22375805 -0.70929937 -0.38883987 -0.66169316 -0.70710678
   1.14190596]
 [ 0.46479907  0.69617712  1.94013791  2.23625729  0.7728383  -0.41803981
  -0.97936664  0.39675948 -0.70929937 -0.72460883 -0.66169316 -0.70710678
   1.14190596]
 [ 0.57683232  0.69617712 -0.92274852 -0.39847623  0.21063328 -0.41803981
  -0.97936664 -0.38174696  1.40984195  1.45788938 -0.66169316  0.26516504
   1.14190596]
 [ 0.8008988   0.69617712  0.98584243 -0.10572806 -0.29535123 -0.41803981
   0.90163913 -0.16549517 -0.70929937  0.61846699 -0.66169316  2.20970869
   1.14190596]
 [-0.7675666   0.69617712 -0.92274852 -0.45702586  0.51047596 -0.41803981
  -0.97936664  0.69951198 -0.70929937 -0.47278211 -0.66169316 -0.70710678
   1.14190596]
 [-1.66383254  0.69617

## Training the Kernel SVM model on the Training set

In [10]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

## Predicting the Test set results

In [11]:
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]]


## Making the Confusion Matrix

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[21  6]
 [ 2 32]]


0.8688524590163934